---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sre-operator-reinstall-sa
  namespace: openshift-must-gather-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sre-operator-reinstall-role
  namespace: openshift-must-gather-operator
rules:
- apiGroups:
  - "operators.coreos.com"
  resources:
  - clusterserviceversions
  - subscriptions
  - installplans
  verbs:
  - list
  - get
  - delete
  - create
- apiGroups:
  - "batch"
  resources:
  - cronjobs
  verbs:
  - list
  - get
  - delete
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - list
  - get
  - delete
- apiGroups:
  - "rbac.authorization.k8s.io"
  resources:
  - roles
  - rolebindings
  verbs:
  - list
  - get
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sre-operator-reinstall-rb
  namespace: openshift-must-gather-operator
roleRef:
  kind: Role
  name: sre-operator-reinstall-role
  apiGroup: rbac.authorization.k8s.io
  namespace: openshift-must-gather-operator
subjects:
- kind: ServiceAccount
  name: sre-operator-reinstall-sa
  namespace: openshift-must-gather-operator

