kind: SecurityContextConstraints
apiVersion: v1
metadata:
  name: pcap-collector
allowPrivilegedContainer: true 
allowHostNetwork: true
allowedCapabilities:
- 'NET_ADMIN'
- 'NET_RAW'
runAsUser:
  type: MustRunAsNonRoot
seLinuxContext:
  type: MustRunAs
