apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pcap-collector
rules:
- apiGroups:
  - security.openshift.io
  resources:
  - securitycontextconstraints
  resourceNames:
  - "pcap-collector"
  verbs:
  - use
