apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pcap-collector 
subjects:
- kind: Group
  name: dedicated-admins
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: pcap-collector
  apiGroup: rbac.authorization.k8s.io
